import 'package:portfolio/app/projects/model/project.dart';
import 'package:portfolio/utilities/constants.dart';

final List<Project> projects = [
  Project(
    name: 'Fitable',
    desc: Constants.fitableDesc(),
    desc2: Constants.fitableDesc2(),
    github: '',
    googlePlay: '',
    image: 'resources/images/fitable/fitable.png',
    images: [
      'resources/images/fitable/1.jpg',
      'resources/images/fitable/2.jpg',
      'resources/images/fitable/3.jpg',
      'resources/images/fitable/4.jpg',
      'resources/images/fitable/5.jpg',
      'resources/images/fitable/6.jpg',
    ],
    benefits: [
      'Dodawanie produktów.',
      'Tworzenie i publikowania własnych przepisów z wideo oraz zdjęciami.',
      'System oceniania i dodawania do ulubionych.',
      'Obserwowanie i wyszukiwanie innych użytkowników lub trenerów.',
      'Wyszukiwarka i skaner kodów kreskowych.',
      'Dodawania pomiarów (waga, tkanka tłuszczowa, obwody ciała).',
      'Synchronizacja z Google Fit (waga, kroki, spalone kalorie).',
      'Wyliczenia BMR wraz z personalizacją.',
    ],
    libraries: ['Flutter', 'Dart', 'Riverpod', 'Firestore', 'Storage', 'Authentication', 'Functions', 'Algolia', 'Localization'],
  ),
  Project(
    name: 'Authentication Riverpod',
    desc: 'Projekt "startowy" wykorzystujący Riverpod napisany głównie w celach edukacyjnych.',
    desc2: '',
    github: 'https://github.com/mniemyjski/authentication_riverpod',
    googlePlay: '',
    image: 'resources/images/authentication/authentication.png',
    images: [
      'resources/images/authentication/1.jpg',
      'resources/images/authentication/2.jpg',
      'resources/images/authentication/3.jpg',
      'resources/images/authentication/4.jpg',
      'resources/images/authentication/5.jpg',
    ],
    benefits: [
      'Autoryzacja email oraz google',
      'Edycja profilu i zdjęcia',
      'Lokalizacja',
      'Tryb Ciemny',
    ],
    libraries: ['Flutter', 'Dart', 'Riverpod', 'Firestore', 'Storage', 'Authentication', 'Localization'],
  ),
  Project(
    name: 'Authentication BloC',
    desc: 'Projekt "startowy" wykorzystujący BloC napisany głównie w celach edukacyjnych.',
    desc2: '',
    github: 'https://github.com/mniemyjski/authentication_bloc',
    googlePlay: '',
    image: 'resources/images/authentication/authentication.png',
    images: [
      'resources/images/authentication/1.jpg',
      'resources/images/authentication/2.jpg',
      'resources/images/authentication/3.jpg',
      'resources/images/authentication/4.jpg',
      'resources/images/authentication/5.jpg',
    ],
    benefits: [
      'Autoryzacja email oraz google',
      'Edycja profilu i zdjęcia',
      'Lokalizacja',
      'Tryb Ciemny',
    ],
    libraries: ['Flutter', 'Dart', 'BLoc', 'Firestore', 'Storage', 'Authentication', 'Localization'],
  ),
  Project(
    name: 'ZPRBOX',
    desc: Constants.zprDesc(),
    image: 'resources/images/zpr/zpr.jpg',
    images: [
      'resources/images/zpr/1.jpg',
    ],
    benefits: [
      'Pobranie najstarszej wolnej reklamacji.',
      'Dodawanie komentarzy.',
      'Przepięcie na inna osobę lub skill.',
      'Zamawianie rozmów.',
      'Dostęp do potrzebnych raportów.',
      'Dostęp do indywidualnego systemu motywacyjnego.',
      'Panel administracyjny dla kadry z raportami i możliwością dodawania nowych użytkowników, zarządzania reklamacjami oraz uprawnieniami.',
    ],
    libraries: ['USERFORM', 'VBA', 'ODBC', 'SQL', 'PL/SQL'],
  ),
];
final List<String> tech = ['Flutter 🔥', 'Dart', 'Firebase', 'SQL', 'PL/SQL', 'VBA'];
